// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVItdVVlWplFNdfyStUzZHtDsECuAOTrs',
    appId: '1:781958227421:web:00aa67083e205569810234',
    messagingSenderId: '781958227421',
    projectId: 'book-recommendation-syst-db24e',
    authDomain: 'book-recommendation-syst-db24e.firebaseapp.com',
    storageBucket: 'book-recommendation-syst-db24e.appspot.com',
    measurementId: 'G-VSSGW1703R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL1zht9D6PRh2wYNK8YE5GpVVpbuUbFBc',
    appId: '1:781958227421:android:495aa0b72971d6d5810234',
    messagingSenderId: '781958227421',
    projectId: 'book-recommendation-syst-db24e',
    storageBucket: 'book-recommendation-syst-db24e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDDFFOW0ouoVO-AlE4G0jmq4p46egoGc',
    appId: '1:781958227421:ios:ac65be0062bbaf8a810234',
    messagingSenderId: '781958227421',
    projectId: 'book-recommendation-syst-db24e',
    storageBucket: 'book-recommendation-syst-db24e.appspot.com',
    iosClientId: '781958227421-qj8obk5mnpo00nu442krdr605rvn63tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookRecommendationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLDDFFOW0ouoVO-AlE4G0jmq4p46egoGc',
    appId: '1:781958227421:ios:ac65be0062bbaf8a810234',
    messagingSenderId: '781958227421',
    projectId: 'book-recommendation-syst-db24e',
    storageBucket: 'book-recommendation-syst-db24e.appspot.com',
    iosClientId: '781958227421-qj8obk5mnpo00nu442krdr605rvn63tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookRecommendationSystem',
  );
}
